// src/components/ExternalAuthStrategy.svelte
<script lang="ts">
  import anylogger from 'anylogger';
  import { onMount } from 'svelte';
  import { redirectUrl, invitationInfo } from '../stores/user';

  const log = anylogger('external-auth-strategy');

  //export let name: string;
  export let id: string;
  export let url: string;
  export let icon: string;
  let invitationToken: string;
  let invitationEmail: string;

  onMount(async () => {
    // Variable that keeps track of the invitation info that is available in the page context, if any
    invitationToken = $invitationInfo.token;
    invitationEmail = $invitationInfo.email;

    // TODO debug
    log.warn(`redirectUrl: ${redirectUrl}`);
    log.warn(`invitation info: ${invitationEmail} / ${invitationToken}`);
  });

  const submitForm = (e: Event) => {
    // TODO
    log.warn('Here I go, using external auth again...');
  };
</script>

<form on:submit|preventDefault={submitForm} action={url} method="POST" class="btn-group is-inline-flex is-align-items-center">
  <input type="hidden" name="invitationToken" bind:value={invitationToken} />
  <input type="hidden" name="invitationEmail" bind:value={invitationEmail} />
  <input type="hidden" name="redirectUrl" bind:value={$redirectUrl} />

  <div>
    <button on:click={submitForm} href="/" class={`${id} button is-round is-light signIn-button is-multiline`}>
      <i class={icon} />
    </button>
  </div>
</form>

<style lang="scss">
  .btn-group {
    margin: 1em 0 1em 5%;
  }

  .icon {
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .button.is-multiline {
    min-width: 2em;
    min-height: 1em;
    white-space: unset;
    height: auto;
  }
</style>

// src/components/external-auth-strategy/external-auth-strategy.tsx
import { Component, h, Prop } from '@stencil/core';
import { getLoginRedirectUrl as getRedirectUrl, getInvitationInfo } from '../../helpers/utils';

import anylogger from 'anylogger';
const log = anylogger('external-auth-strategy');

@Component({
  tag: 'external-auth-strategy',
  styleUrl: 'external-auth-strategy.css',
})
export class ExternalAuthStrategy {
  @Prop() name: string;
  @Prop() id: string;
  @Prop() url: string;
  @Prop() icon: string;
  @Prop() redirectUrl: string;
  @Prop() invitationToken: string;
  @Prop() invitationEmail: string;

  componentWillLoad() {
    this.redirectUrl = getRedirectUrl();

    // Variable that keeps track of the invitation info that is available in the page context, if any
    const invitationInfo = getInvitationInfo();
    this.invitationToken = invitationInfo.token;
    this.invitationEmail = invitationInfo.email;

    // TODO debug
    log.debug(`redirectUrl: ${this.redirectUrl}`);
    log.debug(`invitation info: ${this.invitationEmail} / ${this.invitationToken}`);
  }

  submitForm(e: Event) {
    e.preventDefault();
  }

  render() {
    const socialButtonClass = `${this.id} button is-round signIn-button`;
    return (
      <form action={this.url} method="POST">
        <input type="hidden" name="invitationToken" value={this.invitationToken} />
        <input type="hidden" name="invitationEmail" value={this.invitationEmail} />
        <input type="hidden" name="redirectUrl" value={this.redirectUrl} />
        <a onClick={this.submitForm} class={socialButtonClass}>
          <i class={this.icon}></i>
        </a>
      </form>
    );
  }
}
