// src/routes/Homepage.svelte
<script lang="ts">
  import { _, isLoading } from "svelte-i18n";
  import { onMount } from "svelte";
  import { prop } from "ramda";
  import HomeTopBar from "../components/HomeTopBar.svelte";
  import anylogger from "anylogger";
  import {
    getCurrentUser,
    redirectUrl,
    user,
    tenantConfig,
    invitationInfo,
  } from "../stores/user";
  import { authenticationAPI } from "../helpers/authentication";
  import { getRedirectUrl, getInvitationInfo } from "../helpers/utils";
  import { useFocus } from "svelte-navigator";
  import { locale } from "svelte-i18n";

  let log = anylogger("homepage");
  const registerFocus = useFocus();

  let authenticationStrategy = {};
  export let goToLogin: string;

  let pageTitle;
  $: if ($isLoading) {
    pageTitle = "...";
  } else {
    pageTitle = $_(
      "packages.oae-core.footer.bundles.OPEN_ACADEMIC_ENVIRONMENT"
    );
  }

  onMount(async () => {
    redirectUrl.set(getRedirectUrl(document.location.toString()));
    log.warn(`redirectUrl:`);
    log.warn($redirectUrl);

    // Variable that keeps track of the invitation info that is available in the page context, if any
    invitationInfo.set(getInvitationInfo(document.location.toString()));
    log.warn(
      `invitation info: ${prop("email", $invitationInfo)} / ${prop(
        "token",
        $invitationInfo
      )}`
    );

    try {
      const response = await fetch("/api/config");
      const data = await response.json();
      tenantConfig.set(data);
      log.warn(`tenant configuration: ${tenantConfig}`);

      const askAuthAPI = authenticationAPI();
      // Variable that holds the configured auth strategy information for the tenant
      authenticationStrategy = askAuthAPI.getStrategyInfo($tenantConfig);
      log.warn(`authStrategyInfo: ${authenticationStrategy}`);

      // Get data on the user visiting
      user.set(await getCurrentUser());

      locale.set($user.locale);
    } catch (error) {
      // TODO exception handling
      log.error(`Unable to fetch tenant configuration`, error);
    }
  });
</script>

<svelte:head><title>{pageTitle}</title></svelte:head>

{#if $isLoading}
  Please wait...
{:else}
  <section class="hero is-primary is-medium">
    <HomeTopBar {goToLogin} {authenticationStrategy} />
    <div class="hero-head" />
    <div class="hero-body main-area">
      <div class="container has-text-centered is-centered">
        <p class="title homepage-title">
          {$_("shared.oae.bundles.ui.SUPPORTING_ACADEMIC_COLLABORATION")}
        </p>
        <home-search use:registerFocus />
      </div>
    </div>
    <div class="hero-body section1-area">
      <div class="container has-text-centered is-centered">
        <p class="subtitle">
          The Open Academic Environment is the easiest way to communicate and
          share files with your classmates. Whether you're a student,
          investigator or professor, join us for free!
        </p>
      </div>
    </div>
  </section>
{/if}

<style lang="scss">
  // Font Colour
  $fontColour: #212121;
  $secondaryFontColor: #424242;

  // Import Roboto Slab for Title
  // Single Use
  @import url("https://fonts.googleapis.com/css?family=Roboto:700&display=swap");
  @import url("https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@800&display=swap");

  .hero-body.main-area {
    height: 100px;
    overflow: hidden;
    background-image: url("../assets/images/cool-background.svg");
    background-repeat: no-repeat;
    background-position: right;
    background-size: cover;
    background-color: white;
  }

  .img.background-img {
    visibility: hidden;
  }

  .hero-body.section1-area {
    background-color: hotpink;
  }

  .hero.is-primary .title {
    color: white;
    margin-bottom: 35px;
  }

  .hero .navbar {
    background-color: white;
  }

  // Main Section
  // Title
  .hero-body.main-area.title {
    color: #212121;
  }

  .control.has-icons-left.home-searchIcon {
    text-align: center;
  }

  .input {
    width: 70%;
    border: none;
    box-shadow: none;
    font-weight: bold;
    border-radius: 2px;
  }

  .input.input:hover {
    border: none;
    box-shadow: none;
    -webkit-box-shadow: 0px 1px 6px 0px rgba(50, 50, 50, 0.52);
    -moz-box-shadow: 0px 1px 6px 0px rgba(50, 50, 50, 0.52);
    box-shadow: 0px 1px 6px 0px rgba(50, 50, 50, 0.52);
  }

  .input.input:focus {
    border: none;
    -webkit-box-shadow: 0px 1px 6px 0px rgba(50, 50, 50, 0.52);
    -moz-box-shadow: 0px 1px 6px 0px rgba(50, 50, 50, 0.52);
    box-shadow: 0px 1px 6px 0px rgba(50, 50, 50, 0.52);
  }
</style>

// src/components/homepage/homepage.tsx
/**
 * TODO
 *
 * [ ] firefox debug on vscode
 * [ ] create types for authentication etc
 * [x] clear all linting errors
 * [x] store user on mobx
 *
 */
/* eslint-disable new-cap, @typescript-eslint/promise-function-async */
import { Component, h, Prop } from '@stencil/core';
import { flowResult } from 'mobx';

import { authenticationAPI } from '../../helpers/authentication';
import { getLoginRedirectUrl as getRedirectUrl, getInvitationInfo } from '../../helpers/utils';

import rootStore from '../../stores/root-store';

@Component({
  tag: 'oae-homepage',
  styleUrl: 'homepage.scss',
})
export class Homepage {
  @Prop({ mutable: true }) tenantConfig;
  @Prop({ mutable: true }) authStrategyInfo;
  @Prop({ mutable: true }) currentUser;

  componentWillLoad() {
    const userStore = rootStore.userStore;
    const redirectUrl = getRedirectUrl();
    // TODO debug
    console.log(`redirectUrl: ${redirectUrl}`);

    // Variable that keeps track of the invitation info that is available in the page context, if any
    const invitationInfo = getInvitationInfo();
    // TODO debug
    console.log(`invitation info: ${invitationInfo.email} / ${invitationInfo.token}`);

    return fetch('/api/config')
      .then(response => {
        return response.json();
      })
      .then(data => {
        this.tenantConfig = data;

        // TODO debug
        console.log('this.tenantConfig:');
        console.log(this.tenantConfig);

        return data;
      })
      .then(tenantConfig => {
        const askAuthAPI = authenticationAPI();
        // Variable that holds the configured auth strategy information for the tenant
        this.authStrategyInfo = askAuthAPI.getStrategyInfo(tenantConfig);

        // TODO debug
        console.log('this.authStrategyInfo:');
        console.log(this.authStrategyInfo);

        return this.authStrategyInfo;
      })
      .then(() => {
        // Get data on the user visiting
        return flowResult(userStore.getCurrentUser());
      })
      .then(currentUser => {
        console.log(`login user: ${currentUser}`);

        // TODO maybe we just want to have it in our store
        this.currentUser = currentUser;

        // Store this guy on mobX store, not as a prop?
        userStore.setCurrentUser(currentUser);
        console.log(userStore.describeUser);
      })
      .catch(error => {
        // TODO exception handling
        console.error(error);
      });
  }

  render() {
    return (
      <section class="hero is-primary is-medium">
        <home-nav authStrategyInfo={this.authStrategyInfo} tenantAlias={this.currentUser.tenant.alias}></home-nav>
        <div class="hero-head"></div>
        <div class="hero-body main-area">
          <div class="container has-text-centered is-centered">
            <p class="title homepage-title">A new way to share, explore and connect</p>
            <home-search></home-search>
          </div>
        </div>
        <div class="hero-body section1-area">
          <div class="container has-text-centered is-centered">
            <p class="subtitle">
              The Open Academic Environment is the easiest way to communicate and share files with your classmates. Whether you're a student, investigator or professor, join us for
              free!
            </p>
          </div>
        </div>
      </section>
    );
  }
}
