// src/components/LocalAuthStrategy.svelte
<script lang="ts">
  import anylogger from "anylogger";
  import "@material/mwc-button";
  import "@material/mwc-textfield";
  import { when, equals, defaultTo, prop, compose, isEmpty, not } from "ramda";
  import { useLocation, useNavigate } from "svelte-navigator";
  import { getCurrentUser, redirectUrl, user } from "../stores/user";

  import { resetField } from "../helpers/form";
  import { authenticationAPI } from "../helpers/authentication";
  import { authConstants } from "../helpers/constants";
  import { onMount } from "svelte";

  const navigate = useNavigate();
  const location = useLocation();
  const log = anylogger("local-auth-strategy");

  const { STRATEGY_LDAP, STRATEGY_LOCAL } = authConstants;
  const askAuthAPI = authenticationAPI();
  const {
    tryLDAPFirstLocalAuthSecond: tryLocalIfLdapFails,
    signInViaLDAP: tryLDAPLogin,
    signInViaLocalAuth: tryLocalAuthLogin,
  } = askAuthAPI;

  const ENTER_KEY = "Enter";
  const KEY = "key";

  const isNotEmpty = compose(not, isEmpty);
  const getLdapSettings = compose(defaultTo({}), prop(STRATEGY_LDAP));
  const getLocalSettings = compose(defaultTo({}), prop(STRATEGY_LOCAL));
  const wasEnterKeyPressed = compose(equals(ENTER_KEY), prop(KEY));
  const succededAuthentication = equals(200);
  const failedAuthentication = equals(401);

  export let enabledStrategies;
  let formValidation = { failed: true, message: "" };
  let localAuthForm;
  let usernameField;
  let passwordField;
  let submitButton;

  /**
   * Attempt to log the user in with the provided username and password onto the current
   * tenant using either the LDAP login strategy or the local login strategy. If only one of
   * them is enabled, only that strategy will be attempted. If both of them are enabled, an
   * LDAP login will be attempted first. If that is unsuccessful, a local login will be
   * attempted next.
   */
  const handleSubmit = async (event: Event) => {
    const username = usernameField.value;
    const password = passwordField.value;

    const ldapSettings = getLdapSettings(enabledStrategies);
    const localSettings = getLocalSettings(enabledStrategies);

    const isLocalEnabled: boolean = isNotEmpty(localSettings);
    const isLDAPEnabled: boolean = isNotEmpty(ldapSettings);
    const areBothEnabled = isLocalEnabled && isLDAPEnabled;

    const attemptLogin = async () => {
      switch (true) {
        case areBothEnabled:
          return tryLocalIfLdapFails(
            username,
            password,
            ldapSettings,
            localSettings
          );
        case isLDAPEnabled:
          return tryLDAPLogin(username, password, ldapSettings);
        default:
          return tryLocalAuthLogin(username, password, localSettings);
      }
    };

    try {
      postLogin(await attemptLogin());
    } catch (error) {
      // Username and/or password are missing
      formValidation = { failed: true, message: error.message };
    }
  };

  /**
   * Finish the login process by showing the correct validation message in case of a failed
   * login attempt, or by redirecting the user in case of a successful login attempt
   */
  const postLogin = async (status) => {
    if (succededAuthentication(status)) {
      /**
       * Eventually we will redirect the user to the redirect url
       * In the meantime, while we don't implement all the routes,
       * we'll just move to the activity feed instead
       *
       * TODO: uncomment this line and place it below, one day
       * navigate($redirectUrl);
       */
      formValidation = { failed: false, message: "" };
      log.warn(`Authentication succeeded, redirecting to the activity feed..`);

      const from = ($location.state && $location.state.from) || "/dashboard";
      navigate(from, { replace: true });
    } else if (failedAuthentication(status)) {
      formValidation = { failed: true, message: "Wrong credentials" };
      clearPasswordField();
    }
  };

  const clearPasswordField = () => {
    resetField(passwordField);
    passwordField.focus();
  };

  onMount(async () => {
    submitButton.addEventListener("click", async (event) => {
      await handleSubmit(event);
    });
  });

  const onKeyPress = async (event: KeyboardEvent) => {
    when(wasEnterKeyPressed, handleSubmit, event);
  };
</script>

<form bind:this={localAuthForm} on:submit|preventDefault={handleSubmit}>
  <mwc-textfield
    bind:this={usernameField}
    on:keypress={onKeyPress}
    dialogInitialFocus
    id="username"
    minlength="3"
    maxlength="64"
    placeholder="Username"
    required
  />
  <mwc-textfield
    bind:this={passwordField}
    on:keypress={onKeyPress}
    type="password"
    id="password"
    minlength="3"
    maxlength="64"
    placeholder="Password"
    required
  />
  <mwc-button
    bind:this={submitButton}
    id="submit-button"
    on:click={handleSubmit}
  >
    Sign in
  </mwc-button>

  {#if formValidation.failed}
    <div class="wrong-credentials">{formValidation.message}</div>
  {/if}
</form>

<style lang="scss">
  .wrong-credentials {
    color: red;
    font-weight: bold;
  }
</style>

// src/components/local-auth-strategy/local-auth-strategy.tsx
/* eslint-disable import/no-unassigned-import, new-cap, */
/**
 * TODOs
 * [ ] Disable on submit button on click
 * [x] Submit form and parse response
 * [ ] Spinner somewhere while loading
 * [ ] Display warning if bad credentials
 * [ ] Clear password field after submit if 401 is returned
 * [ ] Focus on username input on loading the modal window
 */
import { Listen, State, Prop, Component, h, Element } from '@stencil/core';
import '@material/mwc-button';
import '@material/mwc-textfield';

import { equals, defaultTo, prop, compose, isEmpty, not } from 'ramda';
const isNotEmpty = compose(not, isEmpty);

import { authenticationAPI } from '../../helpers/authentication';
const askAuthAPI = authenticationAPI();
const { tryLDAPFirstLocalAuthSecond, signInViaLDAP: tryLDAPLogin, signInViaLocalAuth: tryLocalAuthLogin } = askAuthAPI;

import { authConstants } from '../../helpers/constants';
const { STRATEGY_LDAP, STRATEGY_LOCAL } = authConstants;

@Component({
  tag: 'local-auth-strategy',
  styleUrl: 'local-auth-strategy.css',
})
export class LocalAuthStrategy {
  @Prop() enabledStrategies: any;
  @Element() element: HTMLElement;
  @State() validationFailed = false;

  @Listen('keydown')
  async handleKeyDown(event: KeyboardEvent) {
    const wasEnterKeyPressed = compose(equals('Enter'), prop('key'));
    if (wasEnterKeyPressed(event)) {
      return this.handleSubmit(event);
    }
  }

  /**
   * Attempt to log the user in with the provided username and password onto the current
   * tenant using either the LDAP login strategy or the local login strategy. If only one of
   * them is enabled, only that strategy will be attempted. If both of them are enabled, an
   * LDAP login will be attempted first. If that is unsuccessful, a local login will be
   * attempted next.
   */
  async handleSubmit(event: Event) {
    event.preventDefault();

    const usernameField: HTMLInputElement = this.element.querySelector('#username');
    const username = usernameField.value;
    const passwordField: HTMLInputElement = this.element.querySelector('#password');
    const password = passwordField.value;

    const ldapSettings = compose(defaultTo({}), prop(STRATEGY_LDAP))(this.enabledStrategies);
    const isLDAPEnabled: boolean = isNotEmpty(ldapSettings);

    const localSettings = compose(defaultTo({}), prop(STRATEGY_LOCAL))(this.enabledStrategies);
    const isLocalEnabled: boolean = isNotEmpty(localSettings);

    const areBothEnabled = isLocalEnabled && isLDAPEnabled;

    const responseStatus: number = await (async () => {
      switch (true) {
        case areBothEnabled:
          return tryLDAPFirstLocalAuthSecond(username, password, ldapSettings, localSettings);
        case isLDAPEnabled:
          return tryLDAPLogin(username, password, ldapSettings);
        default:
          return tryLocalAuthLogin(username, password, localSettings);
      }
    })();

    this.postLogin(responseStatus);
  }

  /**
   * Finish the login process by showing the correct validation message in case of a failed
   * login attempt, or by redirecting the user in case of a successful login attempt
   */
  postLogin(status) {
    const succededAuthentication = equals(200, status);
    const failedAuthentication = equals(401, status);

    if (succededAuthentication) {
      /**
       * Eventually we will redirect the user to the redirect url
       * In the meantime, while we don't implement all the routes,
       * we'll just move to the activity feed instead
       *
       * TODO: uncomment these lines, one day
       * const userStore = rootStore.userStore;
       * window.location.href = userStore.getUserRedirectUrl();
       */

      this.validationFailed = false;
      window.location.href = '/dashboard';
    } else if (failedAuthentication) {
      // show alert message saying credentials not valid
      this.validationFailed = true;
    }
  }

  componentDidLoad() {
    const button = this.element.querySelector('#submit-button');
    button.addEventListener('click', async event => {
      await this.handleSubmit(event);
    });
  }

  render() {
    let loginFailed;
    if (this.validationFailed) {
      loginFailed = <div>Ouch! credentials not valid</div>;
    }

    return (
      <form onSubmit={this.handleSubmit}>
        <mwc-textfield id="username" minlength="3" maxlength="64" placeholder="Username" required></mwc-textfield>
        <mwc-textfield type="password" id="password" minlength="3" maxlength="64" placeholder="Password" required></mwc-textfield>
        <mwc-button id="submit-button" slot="primaryAction">
          Sign in
        </mwc-button>
        {loginFailed}
      </form>
    );
  }
}
